// pipeline {
//     agent any

//         tools {
//         // Requires ShiningPanda plugin for Python virtualenv
//         python 'Python3'
//     }

//     environment {
//         VENV = 'venv'
//     }

//     stages {
//         stage('Checkout') {
//             steps {
//                 git branch: 'main',
//                     credentialsId: 'github-alx-backend',  // Jenkins credentials ID
//                     url: 'https://github.com/Reaganz-Wat/alx-backend-python.git'
//             }
//         }

//         stage('Setup Python Environment') {
//             steps {
//                 sh '''
//                     python3 -m venv ${VENV}
//                     . ${VENV}/bin/activate
//                 '''
//             }
//         }

//         stage('Install Dependencies') {
//             steps {
//                 sh '''
//                     . ${VENV}/bin/activate
//                     pip install --upgrade pip
//                     pip install -r messaging_app/requirements.txt
//                 '''
//             }
//         }

//         stage('Run Tests') {
//             steps {
//                 sh '''
//                     . ${VENV}/bin/activate
//                     python3 manage.py test chats/tests.py --verbosity=2
//                 '''
//             }
//             post {
//                 always {
//                     junit 'report.xml'
//                 }
//             }
//         }
//     }

//     post {
//         always {
//             archiveArtifacts artifacts: '**/report.xml', fingerprint: true
//         }
//     }
// }



pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-alx-backend',  // Jenkins credentials ID
                    url: 'https://github.com/Reaganz-Wat/alx-backend-python.git'
            }
        }

        stage('Setup & Run Python Environment') {
            steps {
                // This uses ShiningPanda plugin
                withPythonEnv('Python3') { // Name must match your Python installation in Jenkins > Global Tool Config
                    sh '''
                        python -m venv ${VENV}
                        . ${VENV}/bin/activate
                        pip install --upgrade pip
                        pip install -r messaging_app/requirements.txt
                        python manage.py test chats/tests.py --verbosity=2
                    '''
                }
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/report.xml', fingerprint: true
        }
    }
}
