pipeline {
    agent any
    
    tools {
        // This requires ShiningPanda plugin installed and Python configured in Jenkins
        'jenkins.plugins.shiningpanda.tools.PythonInstallation' 'Python3'
    }
    
    environment {
        VENV = 'venv'
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-alx-backend',
                    url: 'https://github.com/Reaganz-Wat/alx-backend-python.git'
            }
        }
        
        stage('Setup Python Environment') {
            steps {
                sh '''
                    python3 -m venv ${VENV}
                    . ${VENV}/bin/activate
                    pip3 install --upgrade pip
                '''
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh '''
                    . ${VENV}/bin/activate
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }
        
        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV}/bin/activate
                    cd messaging_app
                    python3 manage.py test chats.tests --verbosity=2
                '''
            }
            post {
                always {
                    script {
                        if (fileExists('report.xml')) {
                            junit 'report.xml'
                        }
                    }
                }
            }
        }
    }
    
    post {
        always {
            sh 'rm -rf ${VENV}'
            script {
                if (fileExists('**/report.xml')) {
                    archiveArtifacts artifacts: '**/report.xml', fingerprint: true
                }
            }
        }
    }
}